package com.example.rammzexpensetracker.ui.dashboard;

public class Budget {

    String key;
    double budget, totalExpenses;

    // Empty constructor needed for Firebase
    public Budget() {
    }

    // Getter functions for each entry box

    public double getTotalExpenses() {
        return totalExpenses;
    }

    public double getBudget() {
        return budget;
    }

    // gets unique key generated by Firebase
    public String getKey() {
        return key;
    }

    // Setter functions for each entry box variable

    public void setTotalExpenses(double totalExpenses) {
        this.totalExpenses = totalExpenses;
    }

    public void setBudget(double budget) { this.budget = budget; }

    public void setKey(String key) {
        this.key = key;
    }

}
